config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
  root "flats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :edit, :update, :destroy]
  def index
    @number_flat = Flat.count
    if params[:query]
      @flats = Flat.where("name like ?", "%#{params[:query]}%")
    else
      @flats = Flat.all
    end
  end

  def show
  end

  def create
    @flat = Flat.create!(flat_params)
    redirect_to root_path
  end

  def new
    @flat = Flat.new
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to "/"
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name%>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<div class="flat-container">
  <div class="create-container">
    <h1>Add your flat:</h1>
    <%= render "form", flat: @flat %>
  </div>
</div>

app/views/flats/index.html.erb
<div class="flat-container">
<h1>All our flats</h1>
<p>All <%=@number_flat%></p>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-sm-12 col-md-4">
        <div class="card" style="width: 18rem;">
          <img src="https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?cs=srgb&dl=pexels-vecislavas-popa-1571460.jpg&fm=jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%=flat.name%></h5>
            <p class="card-text"><%=flat.address%></p>
          </div>
          <div class="price-info d-flex p-3 mb-0">
            <div class="user_info d-flex align-items-baseline" >
              <i class="fas fa-euro-sign"></i>
              <p><%=flat.price_per_night%>  </p>
            </div>
            <br>
            <div class="user_info d-flex align-items-baseline ml-2">
              <i class="fas fa-user-friends"></i>
              <p><%=flat.number_of_guests%></p>
            </div>
          </div>
          <hr class="my-0">
          <div class="redirect d-flex justify-content-between p-3">
            <%= link_to "More info",  flat_path(flat)%>
            <%= link_to "Edit",  edit_flat_path(flat), class: "edit"%>
            <%= link_to "Remove",  flat_path(flat), method: :delete, data: { confirm: "Delete #{flat.name} ?" }, class: "remove"%>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="flat-container">
  <div class="create-container">
    <h1>Add your flat:</h1>
    <%= render "form", flat: @flat %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="banner">
  <div class="banner-container" style= "background-image: url('https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')">
  </div>
</div>
<div class="container">
  <div class="row ">
  <div class="col-md-9 flat-info-container">
    <div class=" name-address">
      <h1>
        <%=  @flat.name %>
      </h1>
      <h3>
        <%= @flat.address %>
      </h3>
    </div>
    <div class="description">
      <h2>A bit more about this flat...</h2>
      <p>
        <%=@flat.description%>
      </p>
    </div>
    <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=10 Clifton Gardens London W9 1DT&amp;zoom=13&amp;scale=2&amp;size=1000x1000&amp;maptype=roadmap&amp;markers=color:red%7C10 Clifton Gardens London W9 1DT&amp;key=AIzaSyBtaHK-BLhBg7TruJu8iKk_wETqZMJM-GY')">

    </div>
  </div>
  <div class="col-md-3 booking-container">
    <div class="booking">
      <h2>Book this place!</h2>
      <form>
        <div class="col-auto">
          <label class="sr-only" for="inlineFormInputGroup">From</label>
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text">From:</div>
            </div>
            <input type="date" class="form-control" id="inlineFormInputGroup" placeholder="YYYY/MM/DD">
          </div>
        </div>
        <div class="col-auto">
          <label class="sr-only" for="inlineFormInputGroup">To:</label>
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text">To:</div>
            </div>
            <input type="date" class="form-control" id="inlineFormInputGroup" placeholder="YYYY/MM/DD">
          </div>
        </div>
        <div class="d-flex justify-content-center">
          <button type="submit" class="btn btn-primary">Book now</button>
        </div>
      </form>
    </div>
    <div class="details">
      <h3>Details</h3>
      <div class="price-info d-flex">
        <div class="user_info d-flex align-items-baseline" >
          <i class="fas fa-euro-sign"></i>
          <p><%=@flat.price_per_night%>  </p>
        </div>
        <br>
        <div class="user_info d-flex align-items-baseline ml-2">
          <i class="fas fa-user-friends"></i>
          <p><%=@flat.number_of_guests%></p>
      </div>
    </div>

    </div>
    <div class="share d-flex">
      <div class="sharing"><h3>Share</h3></div>
      <div><i class="fa fa-facebook-square fa-2x mr-2"></i></div>
      <div><i class="fa fa-twitter-square fa-2x mr-2"></i></div>
      <div><i class="fa fa-pinterest-square fa-2x mr-2"></i></div>
      <div><i class="fa fa-envelope-square fa-2x"></i></div>
    </div>
  </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/12ab446727.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-expand-md navbar-light d-flex justify-content-between">
    <div class="navbar-container">
      <a class="navbar-brand" href="/">
        <h3>Simple Airbnb</h3>
        <p>Book a flat, live a new experience</p>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>

    <div class="search-container">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline my-2 my-lg-0" action="/">
          <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <%= link_to "Add a flat", new_flat_path, class: "add-new"%>
      </div>
    </div>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>